#!/usr/bin/env python

# BEGIN_COPYRIGHT
#
# Copyright (C) 2014 CRS4.
#
# This file is part of hadoop-galaxy, released under the terms of the BSD
# 3-Clause License <http://opensource.org/licenses/BSD-3-Clause>.
#
# END_COPYRIGHT

import logging

from hadoop_galaxy import main

if __name__ == '__main__':
    logging.basicConfig(level=logging.DEBUG)
    main()
